{% set version = "1.6.0" %}

package:
  name: cymetric
  version: {{ version }}

source:
  git_url: https://github.com/cyclus/cymetric.git
  git_rev: 1.6.0

build:
  number: 3
  skip: True  # [win or osx or py<=27]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cyclus {{ version }}
    - numpy
    - pandas
    - pytables

test:
  requires:
    - pytest
    - cycamore {{ version }}
  imports:
    - cymetric
  source_files:
    - tests

about:
  home: http://fuelcycle.org
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Cyclus Metrics'
  doc_url: http://fuelcycle.org/user/cymetric/index.html
  dev_url: https://github.com/cyclus/cymetric

extra:
  recipe-maintainers:
    - gonuke
    - katyhuff
    - FlanFlanagan
    - bennibbelink
    - munkm
    - abachma2
