{% set version = "dev" %}

package:
  name: cymetric
  version: {{ version }}

source:
  git_url: https://github.com/cyclus/cymetric.git
  git_rev: main

build:
  number: 2
  skip: true  # [win or py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - cyclus {{ version }}
    - numpy
    - pandas
    - pytables

test:
  requires:
    - pytest
    - cycamore {{ version }}
  imports:
    - cymetric
  source_files:
    - tests

about:
  home: http://fuelcycle.org
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Cyclus Metrics'
  doc_url: http://fuelcycle.org/user/cymetric/index.html
  dev_url: https://github.com/cyclus/cymetric

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - katyhuff
    - FlanFlanagan
    - stompsjo
    - bennibbelink
