{% set version = "1.6.0" %}
{% set sha256 = "c5c7ae5b8ac928a23680397db0de54c8aebc2c69add20b37c20407af4be5c199" %}

package:
  name: cymetric
  version: {{ version }}

source:
  fn: cymetric-{{ version }}-{{ sha256 }}.tar.gz
  url: https://github.com/cyclus/cymetric/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or osx or py<=27]

requirements:
  host:
    - python
  run:
    - python
    - cyclus {{ version }}
    - numpy
    - pandas
    - pytables
    - python-graphviz

test:
  requires:
    - nose
    - cycamore {{ version }}
  imports:
    - cymetric
  source_files:
    - tests

about:
  home: http://fuelcycle.org
  license: BSD 3-clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Cyclus Metrics'
  doc_url: http://fuelcycle.org/user/cymetric/index.html
  dev_url: https://github.com/cyclus/cymetric

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - katyhuff
    - FlanFlanagan
    - stompsjo
